# Generated by Django 4.2.17 on 2024-12-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_car_available_remove_car_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='car_images/'),
        ),
    ]
